language: python

python:
    - "2.6"
    - "2.7"
    - "3.4"

# NOTE: Currently, 'develop-deps-ubuntu' is necessary to install pyandoc.
# Actually, it is NOT a test requirement. May we should separate
# requirements-dev.txt from requirements-test.txt.
before_install:
    - sudo make develop-deps-ubuntu

install:
    - pip install -r requirements-dev.txt
    # It's necessary to install the project to create the update-conf.py bin.
    # It's used by the 'test_script.py' module.
    - python setup.py develop

script:
    - make check
    # It's necessary to run tests as 'sudo'. 'sudo' is used by the
    # 'test_sudo_config.py' module.
    - sudo make test
